[package]
name = "theme-manager"
description = "A tiny CLI to help switching between colour themes"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
cmd_lib = "1.9.4"
dirs = "5.0.1"
